name = "woclub"
main = "src/worker.js"
compatibility_date = "2026-08-24"
workers_dev = true

[observability]
enabled = true

[[kv_namespaces]]
binding = "METRICS"
id = "048fa0e573bb4d99862b73ec1ab49fea"
