import { readFile, writeFile } from "node:fs/promises";

const escapeHtml = (value) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");

function render(markdown) {
  const lines = escapeHtml(markdown).split("\n");
  let listOpen = false;
  const output = [];
  for (const line of lines) {
    if (line.startsWith("- ")) {
      if (!listOpen) output.push("<ul>");
      listOpen = true;
      output.push(`<li>${line.slice(2)}</li>`);
      continue;
    }
    if (listOpen) output.push("</ul>");
    listOpen = false;
    if (line.startsWith("## ")) output.push(`<h2>${line.slice(3)}</h2>`);
    else if (line.startsWith("# ")) output.push(`<h1>${line.slice(2)}</h1>`);
    else if (line) output.push(`<p>${line}</p>`);
  }
  if (listOpen) output.push("</ul>");
  return output.join("\n");
}

const [changelog, decisions] = await Promise.all([
  readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8"),
  readFile(new URL("../DECISIONS.md", import.meta.url), "utf8")
]);

const body = `${render(changelog)}<hr>${render(decisions)}`;
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WOCLUB public log</title><style>body{margin:auto;max-width:850px;padding:3rem 1.25rem;background:#101713;color:#e8f0e8;font:16px/1.6 ui-monospace,monospace}h1{color:#b9f36c}h2{margin-top:2.5rem;border-top:1px solid #34453f;padding-top:1.5rem}p,li{color:#b8c5c0}a{color:#b9f36c}hr{margin:4rem 0;border:0;border-top:3px solid #b9f36c}</style></head><body><p><a href="/">← WOCLUB</a> · Generated from the project’s authoritative CHANGELOG.md and DECISIONS.md.</p>${body}</body></html>`;

await writeFile(new URL("../src/generated-log.js", import.meta.url), `// Generated by npm run generate:log; do not edit.\nexport default ${JSON.stringify(html)};\n`);
