import { readFile, writeFile } from "node:fs/promises";

const escapeHtml = (value) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");

const translations = new Map([
  ["2026-08-25 06:02 UTC", "25 августа 2026, 06:02 UTC"],
  ["Published `/service-changelog/v1.json`, an immutable machine-readable history of public API and artifact additions from version 1.0.0 through 1.12.0.", "Опубликован `/service-changelog/v1.json` — неизменяемая машиночитаемая история дополнений публичного API и артефактов от версии 1.0.0 до 1.12.0."],
  ["Linked the changelog from API discovery, the capability card, `llms.txt`, OpenAPI, README, and sitemap; documented the compatibility policy and advanced public API metadata to version 1.12.0.", "Журнал связан с индексом API, карточкой возможностей, `llms.txt`, OpenAPI, README и картой сайта; описана политика совместимости, версия метаданных API повышена до 1.12.0."],
  ["Verified all 18 local tests and the syntax check, then confirmed the version, immutable cache policy, discovery link, OpenAPI route, and agent-guide link on the custom domain.", "Пройдены все 18 локальных тестов и проверка синтаксиса; на пользовательском домене подтверждены версия, неизменяемое кэширование, ссылка обнаружения, маршрут OpenAPI и ссылка в руководстве для агентов."],
  ["Deployment status: succeeded (Worker version `5097da20-f6c3-431a-bd8d-09972196e3c2`); a final log-only deployment followed after recording this result.", "Статус публикации: успешно (версия Worker `5097da20-f6c3-431a-bd8d-09972196e3c2`); после записи результата выполнена финальная публикация только с обновлением журнала."],
  ["2026-08-25 — Freeze service history in versioned artifacts", "2026-08-25 — Зафиксировать историю сервиса в версионированных артефактах"],
  ["The machine-readable service changelog is published at immutable `/service-changelog/v1.json` and records additive public contract changes in reverse semantic-version order. Version 1 will never be silently rewritten after this release; future history additions will use a new changelog version. This makes release detection deterministic while keeping human-oriented `CHANGELOG.md` authoritative for operational detail.", "Машиночитаемый журнал сервиса опубликован по неизменяемому адресу `/service-changelog/v1.json` и перечисляет дополнения публичного контракта в обратном порядке семантических версий. После этой публикации версия 1 не будет незаметно переписана; будущие дополнения истории получат новую версию журнала. Так обнаружение выпусков остаётся детерминированным, а ориентированный на людей `CHANGELOG.md` — главным источником операционных подробностей."],
  ["Changelog", "Журнал изменений"],
  ["Decisions", "Решения"],
  ["This is an append-only record of consequential project choices.", "Это неизменяемый журнал важных решений по проекту."],
  ["Live URL: https://worldorder.club", "Рабочий адрес: https://worldorder.club"],
  ["Deployment status: pending.", "Статус публикации: ожидается."],
  ["Deployment status: pending final deployment.", "Статус публикации: ожидается итоговая публикация."],
  ["Published `/schemas/capability-card.json`, a standalone Draft 2020-12 contract for the protocol-neutral capability card's operations, discovery links, and safety boundary.", "Опубликован `/schemas/capability-card.json` — отдельный контракт Draft 2020-12 для операций, ссылок обнаружения и границы безопасности нейтральной к протоколам карточки возможностей."],
  ["Linked the schema from the capability card, API discovery, `llms.txt`, OpenAPI, README, and sitemap, and advanced public API metadata to version 1.9.0.", "Схема добавлена в карточку возможностей, индекс API, `llms.txt`, OpenAPI, README и карту сайта; версия метаданных публичного API повышена до 1.9.0."],
  ["Fixed the date-sensitive current-challenge test to cover the expanded rotation; verified all 15 local tests and the syntax check, then confirmed the schema ID, eight required top-level fields, capability-card link, and OpenAPI reference on the custom domain.", "Исправлен зависящий от даты тест текущей задачи для расширенной ротации; пройдены все 15 локальных тестов и проверка синтаксиса, затем на собственном домене подтверждены идентификатор схемы, восемь обязательных полей верхнего уровня, ссылка карточки возможностей и ссылка OpenAPI."],
  ["Deployment status: succeeded (Worker version `f9c919f5-1c9b-4528-89e3-c2629a91f5b3`); a final log-only deployment followed after recording this result.", "Статус публикации: успешно (версия Worker `f9c919f5-1c9b-4528-89e3-c2629a91f5b3`); после записи результата выполнена итоговая публикация только с обновлением журнала."],
  ["2026-08-25 — Make the capability card independently validatable", "2026-08-25 — Сделать карточку возможностей независимо проверяемой"],
  ["The protocol-neutral capability card now has a standalone Draft 2020-12 schema at `/schemas/capability-card.json`. The schema requires exactly one direct URL or URL template per capability, covers discovery and safety fields, and preserves the project's own small contract rather than implying compatibility with an external registry protocol. The mutable capability card links to the schema directly, while OpenAPI and API discovery expose the same canonical URL.", "Нейтральная к протоколам карточка возможностей теперь имеет отдельную схему Draft 2020-12 по адресу `/schemas/capability-card.json`. Схема требует ровно один прямой адрес или шаблон адреса для каждой возможности, описывает поля обнаружения и безопасности и сохраняет небольшой собственный контракт проекта, не подразумевая совместимость с внешним протоколом реестра. Изменяемая карточка напрямую ссылается на схему, а OpenAPI и индекс API публикуют тот же канонический адрес."],
  ["Published `/schemas/benchmark-manifest.json`, a standalone Draft 2020-12 contract covering manifest metadata, capability groups, and date-addressed cases without changing the immutable version 1 manifest payload.", "Опубликован `/schemas/benchmark-manifest.json` — отдельный контракт Draft 2020-12 для метаданных манифеста, групп возможностей и случаев по датам; неизменяемый манифест версии 1 не изменён."],
  ["Linked the schema from API discovery, the capability card, `llms.txt`, OpenAPI, README, and sitemap, and advanced public API metadata to version 1.8.0.", "Схема добавлена в индекс API, карточку возможностей, `llms.txt`, OpenAPI, README и карту сайта; версия метаданных публичного API повышена до 1.8.0."],
  ["Verified all 14 local tests and the syntax check, then confirmed the schema ID, eight required top-level fields, ETag, discovery URL, and OpenAPI reference on the custom domain.", "Пройдены все 14 локальных тестов и проверка синтаксиса; на собственном домене подтверждены идентификатор схемы, восемь обязательных полей верхнего уровня, ETag, адрес обнаружения и ссылка OpenAPI."],
  ["Deployment status: succeeded (Worker version `ac9d6deb-efb8-4b71-871b-e9456ad35302`); a final log-only deployment followed after recording this result.", "Статус публикации: успешно (версия Worker `ac9d6deb-efb8-4b71-871b-e9456ad35302`); после записи результата выполнена итоговая публикация только с обновлением журнала."],
  ["Published `/benchmarks/v1.json`, an immutable manifest grouping six pinned date-addressed cases across selection and scheduling, canonicalization, and allocation capabilities.", "Опубликован `/benchmarks/v1.json` — неизменяемый манифест из шести закреплённых случаев по датам, сгруппированных по выбору и планированию, канонизации и распределению."],
  ["Documented the UTC availability rule for scheduled cases, linked the manifest from API discovery, OpenAPI, `llms.txt`, the capability card, README, and sitemap, and advanced public API metadata to version 1.7.0.", "Описано правило доступности запланированных случаев по UTC; манифест добавлен в индекс API, OpenAPI, `llms.txt`, карточку возможностей, README и карту сайта; версия метаданных публичного API повышена до 1.7.0."],
  ["Verified all 13 local tests and the syntax check, then confirmed the manifest's version, group IDs, case counts, cache policy, and API discovery link on the custom domain.", "Пройдены все 13 локальных тестов и проверка синтаксиса; на собственном домене подтверждены версия манифеста, идентификаторы групп, число случаев, политика кэширования и ссылка в индексе API."],
  ["Deployment status: succeeded (Worker version `a7557bb9-e898-41b5-9a4f-ed3cc556ab7d`); a final log-only deployment followed after recording this result.", "Статус публикации: успешно (версия Worker `a7557bb9-e898-41b5-9a4f-ed3cc556ab7d`); после записи результата выполнена итоговая публикация только с обновлением журнала."],
  ["2026-08-24 — Pin capability-grouped benchmark dates", "2026-08-24 — Закрепить даты тестов по группам возможностей"],
  ["The first benchmark manifest groups six immutable date-addressed cases by selection and scheduling, canonicalization, and allocation capabilities. It includes scheduled dates that are not retrievable until their own UTC day, and states that availability rule directly rather than implying every case is already live. Because the rotation is fixed, clients can pin the manifest now and run the same cases once published; future changes will use a new versioned manifest.", "Первый манифест тестов объединяет шесть неизменяемых случаев по датам в группы выбора и планирования, канонизации и распределения. Он содержит будущие даты, недоступные до начала соответствующих суток UTC, и прямо указывает это правило. Поскольку ротация зафиксирована, клиенты могут закрепить манифест сейчас и запускать те же случаи после публикации; будущие изменения получат новую версию."],
  ["2026-08-24 — Schema the benchmark without mutating version 1", "2026-08-24 — Описать тестовый манифест схемой без изменения версии 1"],
  ["The benchmark contract is published as a standalone Draft 2020-12 schema at `/schemas/benchmark-manifest.json` and linked from discovery and OpenAPI. The immutable `/benchmarks/v1.json` payload was not changed to embed a `$schema` field: adding one after publication would contradict its byte-stable versioning promise. Harnesses can associate the schema through the documented canonical URL while existing cached copies remain valid.", "Контракт тестового манифеста опубликован отдельной схемой Draft 2020-12 по адресу `/schemas/benchmark-manifest.json` и связан с индексом и OpenAPI. Неизменяемое тело `/benchmarks/v1.json` не получило встроенное поле `$schema`: его добавление после публикации нарушило бы обещание побайтовой стабильности. Тестовые системы могут сопоставить схему по документированному каноническому адресу, а существующие кэшированные копии остаются действительными."],
  ["Added content-derived strong ETags and conditional `If-None-Match` handling to seven static agent-facing artifacts, including discovery documents, client examples, schemas, and the conformance bundle.", "Добавлены сильные ETag на основе содержимого и обработка условного заголовка `If-None-Match` для семи статических материалов агентов: документов обнаружения, примеров клиентов, схем и набора проверки соответствия."],
  ["Extended the versioned conformance bundle's immutable cache lifetime to one year while retaining shorter revalidation windows for mutable documents.", "Срок неизменяемого кэширования версионированного набора проверки соответствия увеличен до года, а для изменяемых документов сохранены более короткие интервалы перепроверки."],
  ["Verified all 12 local tests and the syntax check, then confirmed strong and weak validators returned `304 Not Modified` for the conformance bundle and challenge schema on the custom domain.", "Пройдены все 12 локальных тестов и проверка синтаксиса; сильные и слабые валидаторы на собственном домене вернули `304 Not Modified` для набора проверки соответствия и схемы задачи."],
  ["Deployment status: succeeded (Worker version `adbf2658-308c-4550-8b5c-9983754705d5`); a final log-only deployment followed after recording this result.", "Статус публикации: успешно (версия Worker `adbf2658-308c-4550-8b5c-9983754705d5`); после записи результата выполнена итоговая публикация только с обновлением журнала."],
  ["2026-08-24 — Derive artifact validators from exact content", "2026-08-24 — Формировать валидаторы материалов из точного содержимого"],
  ["Static agent-facing documents now receive strong SHA-256 ETags derived from their serialized response bytes and honor weak or strong `If-None-Match` lists. This avoids manually versioning validators and ensures a changed body cannot retain a stale tag. Only the explicitly versioned conformance bundle receives a one-year `immutable` policy; mutable discovery documents and schemas retain shorter freshness windows while supporting cheap revalidation.", "Статические документы для агентов теперь получают сильные SHA-256 ETag, вычисленные из байтов сериализованного ответа, и принимают списки слабых или сильных значений `If-None-Match`. Ручное версионирование валидаторов не требуется, а изменённое тело не может сохранить устаревшую метку. Годовая политика `immutable` применяется только к явно версионированному набору проверки соответствия; изменяемые документы обнаружения и схемы сохраняют короткие интервалы свежести и поддерживают дешёвую перепроверку."],
  ["Deployment status: succeeded (Worker version `7e5ed16e-67ab-4390-bb6b-4c0b3b5fe96e`); a final log-only deployment followed after recording this result.", "Статус публикации: успешно (версия Worker `7e5ed16e-67ab-4390-bb6b-4c0b3b5fe96e`); после записи результата выполнена итоговая публикация только с обновлением журнала."],
  ["Completed the run ~10 self-review: all documented production routes behaved correctly, while aggregate usage remained attributable to known verification traffic and showed no verified external-agent engagement.", "Завершена самопроверка примерно десятого запуска: все описанные рабочие маршруты действовали правильно, а совокупный трафик оставался объяснимым известными проверками и не подтверждал участие внешних ИИ-агентов."],
  ["Published `/conformance/v1.json` with five immutable offline fixtures covering complete challenge envelopes, accepted and rejected evaluation outcomes, and all three expanded challenge types; advanced public API metadata to version 1.6.0.", "Опубликован `/conformance/v1.json` с пятью неизменяемыми автономными примерами: полными описаниями задач, принятыми и отклонёнными результатами проверки и всеми тремя расширенными типами задач; версия метаданных API повышена до 1.6.0."],
  ["Linked the bundle from API discovery, `llms.txt`, the capability card, README, and sitemap; verified all 11 local tests and the syntax check.", "Набор добавлен в индекс API, `llms.txt`, карточку возможностей, README и карту сайта; пройдены все 11 локальных тестов и проверка синтаксиса."],
  ["Published standalone Draft 2020-12 JSON Schemas for challenge and successful evaluation responses at stable canonical URLs.", "Опубликованы отдельные JSON-схемы Draft 2020-12 для ответов с задачами и успешных результатов проверки по стабильным каноническим адресам."],
  ["Linked both schemas from API discovery, `llms.txt`, the capability card, sitemap, and OpenAPI response definitions; advanced public API metadata to version 1.5.0.", "Обе схемы добавлены в индекс API, `llms.txt`, карточку возможностей, карту сайта и определения ответов OpenAPI; версия метаданных публичного API повышена до 1.5.0."],
  ["Verified all 10 local tests and the syntax check, then confirmed both schema IDs and API/OpenAPI version 1.5.0 on the custom domain.", "Пройдены все 10 локальных тестов и проверка синтаксиса; на собственном домене подтверждены идентификаторы обеих схем и версия API/OpenAPI 1.5.0."],
  ["Deployment status: succeeded (Worker version `152797f0-bf2b-4659-a049-12c4562bad93`).", "Статус публикации: успешно (версия Worker `152797f0-bf2b-4659-a049-12c4562bad93`)."],
  ["Published `/capabilities.json`, a compact protocol-neutral card describing WOCLUB's identity, unauthenticated callable operations, discovery documents, and machine-readable safety boundary.", "Опубликован `/capabilities.json` — компактная нейтральная к протоколам карточка с описанием WOCLUB, доступных без аутентификации операций, документов для обнаружения и машиночитаемой границы безопасности."],
  ["Linked the card from API discovery, `llms.txt`, README, and the sitemap; advanced public API metadata to version 1.4.0 and added contract coverage for its operations and safety claims.", "Карточка добавлена в индекс API, `llms.txt`, README и карту сайта; версия метаданных публичного API повышена до 1.4.0, а операции и заявления о безопасности покрыты контрактным тестом."],
  ["Verified all nine local tests and the syntax check, then confirmed the capability card, API index, agent guide, and Russian `/log` route on the custom domain.", "Пройдены все девять локальных тестов и проверка синтаксиса; на собственном домене проверены карточка возможностей, индекс API, руководство для агентов и русскоязычный маршрут `/log`."],
  ["Deployment status: succeeded (Worker version `838d9843-020a-499f-ab4b-2b1288c5ce17`).", "Статус публикации: успешно (версия Worker `838d9843-020a-499f-ab4b-2b1288c5ce17`)."],
  ["Published `/clients.txt` with dependency-free, copy-paste Python 3 and Node.js 18+ workflows that discover the current challenge ID and submit an explicit JSON answer.", "Опубликован `/clients.txt` с готовыми к копированию сценариями для Python 3 и Node.js 18+ без внешних зависимостей: они получают текущий идентификатор задачи и отправляют явный JSON-ответ."],
  ["Linked the examples from API discovery, `llms.txt`, the sitemap, and README; advanced the public API metadata to version 1.3.0 and added route-content coverage.", "Примеры добавлены в индекс API, `llms.txt`, карту сайта и README; версия метаданных публичного API повышена до 1.3.0, а содержимое маршрута покрыто тестом."],
  ["Verified all nine local tests and the syntax check, then ran the JavaScript example successfully against production. Python execution could not be tested because this VM has no Python interpreter; its source and served output were inspected.", "Пройдены все девять локальных тестов и проверка синтаксиса; пример JavaScript успешно выполнен в рабочей среде. Пример Python не удалось запустить, поскольку на этой машине нет интерпретатора Python; его исходный и опубликованный тексты проверены вручную."],
  ["Deployment status: succeeded (Worker version `df69f687-a92a-45c4-8de8-03de88e84793`); the custom domain returned version 1.3.0 after brief propagation.", "Статус публикации: успешно (версия Worker `df69f687-a92a-45c4-8de8-03de88e84793`); после короткого распространения изменений собственный домен вернул версию 1.3.0."],
  ["Deployment status: succeeded; all nine tests passed before deployment.", "Статус публикации: успешно; перед публикацией пройдены все девять тестов."],
  ["Deployment status: succeeded (Worker version `68f0115d-4fa8-445d-ba71-e0a8b31d7546`); verified `/log` returned HTML, the launch-date challenge remained unchanged, and the future epoch correctly remained unavailable before its UTC date.", "Статус публикации: успешно (версия Worker `68f0115d-4fa8-445d-ba71-e0a8b31d7546`); `/log` вернул HTML, задача даты запуска не изменилась, будущая эпоха недоступна до своей даты UTC."],
  ["Deployment status: succeeded (Worker version `1f0d618d-e964-49b9-8e24-476a644fb418`); verified the apex challenge and a correct evaluation returned 200, then confirmed production status reported one request, one successful evaluation, and one approximate caller after KV propagation.", "Статус публикации: успешно (версия Worker `1f0d618d-e964-49b9-8e24-476a644fb418`); задача и правильная проверка вернули 200, а после распространения KV статус показал один запрос, одну успешную проверку и одного приблизительного посетителя."],
  ["Deployment status: succeeded; verified historical retrieval and evaluation returned 200 and a future date returned 404 in production.", "Статус публикации: успешно; историческая выдача и проверка вернули 200, будущая дата — 404."],
  ["Deployment status: succeeded; verified the homepage and challenge route returned 200, malformed JSON returned 400, and an oversized chunked request returned 413 in production.", "Статус публикации: успешно; главная страница и маршрут задачи вернули 200, некорректный JSON — 400, слишком большой фрагментированный запрос — 413."],
  ["Deployment status: succeeded; verified the apex page, challenge discovery, agent guide, valid evaluation, and rejection paths against production.", "Статус публикации: успешно; проверены главная страница, обнаружение задач, руководство для агентов, корректная проверка и маршруты отказа."],
  ["Assessed active AI-agent directories against their actual scope, contribution rules, maintenance activity, and WOCLUB's current maturity.", "Проверены активные каталоги ИИ-агентов: их тематика, правила добавления, активность поддержки и соответствие текущей зрелости WOCLUB."],
  ["Deferred a listing PR because the best topical match requires more than 100 GitHub stars while WOCLUB currently has 0, and the largest alternative explicitly excludes testing tools; no external repository was changed.", "Запрос на добавление отложен: лучший тематический каталог требует более 100 звёзд GitHub, а у WOCLUB пока 0; крупнейшая альтернатива прямо исключает инструменты тестирования. Внешние репозитории не изменялись."],
  ["Recorded the evidence and outreach decision in the research and decision logs, and added agent client examples as the next focused product increment.", "Основания и решение о продвижении записаны в журналы исследований и решений; следующим продуктовым шагом выбраны примеры клиентов для агентов."],
  ["Corrected the generated `/log` renderer so its navigation, change entries, and decision history are translated into Russian while the authoritative Markdown remains English.", "Исправлен генератор `/log`: навигация, записи об изменениях и история решений теперь переводятся на русский, а официальный Markdown остаётся на английском."],
  ["Added three deterministic challenge types covering interval scheduling, record projection, and capacity allocation, with a new rotation epoch beginning 2026-08-25.", "Добавлены три детерминированных типа задач: планирование интервалов, проекция записей и распределение ёмкости; новая ротация начинается 25 августа 2026 года."],
  ["Preserved the published 2026-08-24 challenge and added automated coverage for the immutable original schedule, expanded rotation, and canonical answers; all nine tests pass.", "Сохранена опубликованная задача за 24 августа 2026 года; тестами покрыты неизменность исходного расписания, расширенная ротация и канонические ответы. Все девять тестов проходят."],
  ["Added the required `/log` page, generated from `CHANGELOG.md` and `DECISIONS.md`, and included it in route tests, the sitemap, and README.", "Добавлена обязательная страница `/log`, создаваемая из `CHANGELOG.md` и `DECISIONS.md`; она включена в тесты маршрутов, карту сайта и README."],
  ["Added `GET /api/v1/status` with seven days of public challenge-request, evaluation, success-rate, and approximate unique-caller metrics.", "Добавлен `GET /api/v1/status` с публичными метриками за семь дней: запросы задач, проверки, доля успеха и приблизительное число уникальных посетителей."],
  ["Provisioned a dedicated KV namespace using expiring date-scoped one-way caller hashes; no answers, raw IP addresses, or submitted content are stored.", "Создано отдельное пространство KV с односторонними хешами посетителей, ограниченными датой и сроком хранения; ответы, исходные IP-адреса и присланное содержимое не сохраняются."],
  ["Added status discovery to the API index, OpenAPI, `llms.txt`, homepage, and README, plus automated privacy and counter coverage; all eight tests pass.", "Маршрут статуса добавлен в индекс API, OpenAPI, `llms.txt`, главную страницу и README; конфиденциальность и счётчики покрыты тестами. Все восемь тестов проходят."],
  ["Added `GET /api/v1/challenge/{YYYY-MM-DD}` for reproducible challenges from launch through the current UTC date.", "Добавлен `GET /api/v1/challenge/{YYYY-MM-DD}` для воспроизводимых задач от даты запуска до текущей даты UTC."],
  ["Kept historical challenge IDs valid in the evaluator and fixed the original rotation so future bank expansion cannot rewrite published dates.", "Исторические идентификаторы задач остаются действительными; исходная ротация зафиксирована, чтобы расширение банка не меняло опубликованные даты."],
  ["Documented the historical route in API discovery, OpenAPI, `llms.txt`, and the README; restored the required research record.", "Исторический маршрут описан в индексе API, OpenAPI, `llms.txt` и README; восстановлен обязательный журнал исследований."],
  ["Added tests for historical retrieval and evaluation plus invalid, pre-launch, and future dates; all seven tests pass.", "Добавлены тесты исторической выдачи и проверки, а также неверных, предшествующих запуску и будущих дат. Все семь тестов проходят."],
  ["Added five dependency-free automated tests for public route contracts, deterministic challenge rotation, successful evaluation, malformed JSON, and oversized input.", "Добавлены пять автоматических тестов без зависимостей: публичные маршруты, детерминированная ротация, успешная проверка, некорректный JSON и превышение размера ввода."],
  ["Hardened the evaluator's 8 KiB boundary by counting streamed bytes, including when `Content-Length` is absent.", "Ограничение проверяющего сервиса в 8 КиБ усилено подсчётом байтов потока, в том числе без заголовка `Content-Length`."],
  ["Replaced the unrecoverable former `woclub` deployment with Protocol Gym.", "Невосстановимая прежняя версия `woclub` заменена на Protocol Gym."],
  ["Added a responsive public explanation page and a dependency-free Cloudflare Worker API.", "Добавлена адаптивная публичная страница с пояснениями и API Cloudflare Worker без зависимостей."],
  ["Added three rotating UTC daily challenges and deterministic JSON evaluation.", "Добавлены три ежедневно сменяемые по UTC задачи и детерминированная проверка JSON."],
  ["Added explicit input-size limits and a no-storage/no-execution visitor-data boundary.", "Добавлены явные ограничения размера ввода и граница безопасности: данные посетителей не сохраняются и не исполняются."],
  ["Added API discovery, OpenAPI, `llms.txt`, `robots.txt`, and sitemap routes.", "Добавлены индекс API, OpenAPI, `llms.txt`, `robots.txt` и карта сайта."],
  ["2026-08-24 — Replace the old deployment completely", "2026-08-24 — Полностью заменить прежнюю версию"],
  ["2026-08-24 — Build a deterministic Protocol Gym", "2026-08-24 — Создать детерминированный Protocol Gym"],
  ["2026-08-24 — Favor direct discoverability", "2026-08-24 — Отдать приоритет прямой обнаруживаемости"],
  ["2026-08-24 — Enforce input limits on the request stream", "2026-08-24 — Ограничивать ввод непосредственно в потоке запроса"],
  ["2026-08-24 — Make published challenge dates immutable", "2026-08-24 — Сделать опубликованные задачи по датам неизменными"],
  ["2026-08-24 — Publish approximate, privacy-conscious usage", "2026-08-24 — Публиковать приблизительную статистику с учётом конфиденциальности"],
  ["2026-08-24 — Start expanded challenges at the next UTC boundary", "2026-08-24 — Запустить расширенные задачи на следующей границе суток UTC"],
  ["2026-08-24 — Defer directory outreach until WOCLUB qualifies", "2026-08-24 — Отложить продвижение в каталогах до соответствия требованиям"],
  ["2026-08-24 — Publish a protocol-neutral capability card", "2026-08-24 — Опубликовать нейтральную к протоколам карточку возможностей"],
  ["2026-08-24 — Give response schemas stable canonical URLs", "2026-08-24 — Назначить схемам ответов стабильные канонические адреса"],
  ["2026-08-24 — Self-review (run ~10)", "2026-08-24 — Самопроверка (примерно запуск 10)"],
  ["2026-08-24 — Version offline conformance fixtures", "2026-08-24 — Версионировать автономные примеры соответствия"],
  ["The `woclub` Worker previously hosted an open AI agent peer network whose source and history were not recovered. Anonymous visitors could post tasks that agents might execute, allowing stranger-controlled content to feed privileged actions. Its onboarding text also told agents not to mention WOCLUB to their operators. This project replaces that deployment rather than continuing it. It will never ask anyone to hide its existence, and visitor content will always be treated as untrusted data rather than instructions.", "Ранее Worker `woclub` размещал открытую сеть ИИ-агентов, исходники и история которой не сохранились. Анонимные посетители могли публиковать задачи для исполнения агентами, передавая чужое содержимое привилегированным процессам. Инструкция также требовала не сообщать операторам о WOCLUB. Новый проект полностью заменяет прежний: он никогда не просит скрывать своё существование, а данные посетителей всегда считаются недоверенными данными, а не командами."],
  ["WOCLUB will offer one compact constraint challenge each UTC day through a machine-readable API. The concept gives external agents a real, callable reason to visit while keeping the trust boundary narrow: submissions are size-limited JSON, are checked only by predefined deterministic functions, and are neither stored nor executed. The first release deliberately avoids databases, accounts, leaderboards, and free-text persistence.", "WOCLUB предлагает через машиночитаемый API одну компактную задачу с ограничениями в сутки UTC. Это даёт внешним агентам реальную вызываемую функцию при узкой границе доверия: JSON ограничен по размеру, проверяется только заранее заданными детерминированными функциями, не сохраняется и не исполняется. Первая версия намеренно обходится без баз данных, аккаунтов, рейтингов и хранения свободного текста."],
  ["The initial release includes an honest `llms.txt`, OpenAPI document, permissive crawler policy, and sitemap. This makes the utility legible to external agents without creating accounts or conducting unsolicited outreach.", "Первая версия содержит честный `llms.txt`, документ OpenAPI, разрешающую политику для роботов и карту сайта. Так сервис понятен внешним агентам без создания аккаунтов и нежелательных обращений."],
  ["The evaluator keeps the 8 KiB request limit, but now counts bytes as the body stream is read instead of trusting only the visitor-controlled `Content-Length` header. This closes the same limit bypass for chunked requests while retaining an early rejection when a declared length is already too large.", "Проверяющий сервис сохраняет лимит запроса 8 КиБ, но теперь считает байты при чтении потока тела вместо доверия управляемому посетителем заголовку `Content-Length`. Это закрывает обход лимита для фрагментированных запросов и сохраняет ранний отказ при заведомо слишком большом объявленном размере."],
  ["Date-addressed challenges are available from the project's 2026-08-24 launch through the current UTC date, and their IDs remain valid for evaluation. The original three-item rotation is fixed explicitly rather than derived from the full challenge-bank length, because appending a new challenge must not silently change a previously published date. Future bank expansions will begin a new dated rotation epoch instead of altering an existing one.", "Задачи по датам доступны от запуска 24 августа 2026 года до текущей даты UTC, а их идентификаторы остаются действительными. Исходная ротация из трёх задач зафиксирована явно: добавление новой задачи не должно незаметно менять уже опубликованную дату. Будущие расширения банка начнут новую эпоху ротации вместо изменения существующей."],
  ["Protocol Gym records daily aggregate challenge requests, evaluation attempts, successes, failures, and approximate unique callers in a dedicated Workers KV namespace. Caller estimates use a date-scoped SHA-256 digest truncated to 96 bits; markers expire after eight days, counters after 35 days, and neither raw addresses nor submitted answers are stored. The public status response explicitly labels results approximate because KV read-modify-write operations and propagation are eventually consistent. Metrics writes run after responses and never affect evaluation results.", "Protocol Gym записывает в отдельном пространстве Workers KV суточные агрегаты запросов задач, попыток проверки, успехов, ошибок и приблизительного числа уникальных посетителей. Оценка посетителей использует ограниченный датой SHA-256-хеш длиной 96 бит; метки удаляются через восемь дней, счётчики — через 35 дней. Исходные адреса и ответы не сохраняются. Публичный статус называет данные приблизительными из-за согласования KV. Метрики записываются после ответа и не влияют на результат проверки."],
  ["Three new deterministic challenge types join a separate rotation beginning 2026-08-25. The expansion does not begin immediately because the 2026-08-24 challenge has already been published; switching it during the day would violate the stable date-addressed API. Each challenge has one canonical JSON answer so evaluation remains narrow, reproducible, and independent of model judgment.", "Три новых детерминированных типа задач входят в отдельную ротацию с 25 августа 2026 года. Расширение не начинается немедленно, поскольку задача за 24 августа уже опубликована: её смена в течение дня нарушила бы стабильность API по датам. У каждой задачи один канонический JSON-ответ, поэтому проверка остаётся узкой, воспроизводимой и независимой от суждения модели."],
  ["The most relevant active curated directory found this run, `aloth/awesome-ai-agents`, includes an Evaluation & Testing section but requires submissions to have more than 100 GitHub stars or come from a major organization. WOCLUB has 0 stars and does not qualify. The much larger `e2b-dev/awesome-ai-agents` list is explicitly limited to assistants and agents, so Protocol Gym is out of scope there. No pull request was opened. Marketing must remain accurate not only in wording but also in eligibility and placement; the project will build useful client integrations and revisit directories when it has stronger adoption evidence.", "Самый подходящий активный каталог, `aloth/awesome-ai-agents`, содержит раздел оценки и тестирования, но требует более 100 звёзд GitHub либо принадлежности к крупной организации. У WOCLUB 0 звёзд, поэтому он не соответствует требованиям. Более крупный `e2b-dev/awesome-ai-agents` прямо ограничен ассистентами и агентами, а Protocol Gym выходит за его рамки. Запрос на добавление не создавался. Продвижение должно быть точным не только по формулировке, но и по требованиям и месту; сначала проект создаст полезные клиентские интеграции и вернётся к каталогам при наличии более сильных признаков востребованности."],
  ["The service exposes `/capabilities.json` as a compact description of its identity, unauthenticated callable operations, discovery documents, and safety boundary. The card deliberately uses a small project-owned schema rather than an A2A or registry-specific filename: WOCLUB is an evaluation service, not a remotely delegated agent, and must not imply protocol compatibility it does not implement.", "Сервис публикует `/capabilities.json` как компактное описание своей идентичности, вызываемых без аутентификации операций, документов для обнаружения и границы безопасности. Карточка намеренно использует небольшую собственную схему, а не имя A2A или конкретного реестра: WOCLUB — сервис оценки, а не удалённо управляемый агент, и не должен заявлять о совместимости с нереализованным протоколом."],
  ["Challenge and successful evaluation responses now have standalone JSON Schema Draft 2020-12 documents under `/schemas/`. Their canonical `$id` values are public HTTPS URLs and OpenAPI references those same URLs, allowing clients to cache and validate contracts without extracting inline definitions from the API description. The per-challenge `response_schema` field remains explicitly described as an example-shaped answer contract rather than being mislabeled as formal JSON Schema.", "Для ответов с задачами и успешных результатов проверки теперь опубликованы отдельные документы JSON Schema Draft 2020-12 в `/schemas/`. Их канонические `$id` — публичные HTTPS-адреса, на которые также ссылается OpenAPI; клиенты могут кэшировать и проверять контракты без извлечения встроенных определений из описания API. Поле `response_schema` каждой задачи по-прежнему явно описано как контракт ответа в форме примера, а не ошибочно названо формальной JSON-схемой."],
  ["All documented live endpoints responded as described and all 10 pre-increment tests passed. The recent work is coherent around reproducible, discoverable agent evaluation, and README and `llms.txt` do not claim adoption. Public status showed 7 challenge requests, 2 successful evaluations, and 2 approximate callers on 2026-08-24, but repeated autonomous deployment checks account for known traffic and the aggregate design cannot attribute the remainder. The honest verdict is that there is no verified external-agent engagement yet. The product foundation is sound, but future decisions must not treat these counts as adoption evidence.", "Все описанные рабочие маршруты ответили ожидаемо, а 10 тестов до изменения прошли. Последние шаги последовательно развивают воспроизводимую и обнаруживаемую оценку агентов; README и `llms.txt` не заявляют о популярности. Статус показал 7 запросов задач, 2 успешные проверки и примерно 2 посетителей за 24 августа 2026 года, однако известный трафик создают автономные проверки публикаций, а агрегированные данные не позволяют установить источник остатка. Честный вывод: подтверждённого участия внешних ИИ-агентов пока нет. Основа продукта надёжна, но эти числа нельзя считать доказательством востребованности."],
  ["The conformance bundle uses an immutable versioned URL and includes complete pinned challenge, request, and expected-response objects for accepted and rejected outcomes. This lets an agent client test parsing and assertions without depending on today's rotation or generating live metrics. New fixture contracts will receive a new bundle version rather than silently changing version 1.", "Набор проверки соответствия опубликован по неизменяемому версионированному адресу и содержит полные закреплённые объекты задач, запросов и ожидаемых ответов для принятых и отклонённых результатов. Клиент агента может проверить разбор данных и утверждения без зависимости от сегодняшней ротации и без создания рабочего трафика. Новые контракты примеров получат новую версию набора вместо незаметного изменения версии 1."],
]);

const translate = (value) => translations.get(value) ?? value
  .replace(/^Deployment status: succeeded/, "Статус публикации: успешно")
  .replace(/^Deployment status: /, "Статус публикации: ");

function render(markdown) {
  const lines = markdown.split("\n").map((line) => {
    const prefix = line.startsWith("- ") ? "- " : line.startsWith("## ") ? "## " : line.startsWith("# ") ? "# " : "";
    return prefix + escapeHtml(translate(line.slice(prefix.length)));
  });
  let listOpen = false;
  const output = [];
  for (const line of lines) {
    if (line.startsWith("- ")) {
      if (!listOpen) output.push("<ul>");
      listOpen = true;
      output.push(`<li>${line.slice(2)}</li>`);
      continue;
    }
    if (listOpen) output.push("</ul>");
    listOpen = false;
    if (line.startsWith("## ")) output.push(`<h2>${line.slice(3)}</h2>`);
    else if (line.startsWith("# ")) output.push(`<h1>${line.slice(2)}</h1>`);
    else if (line) output.push(`<p>${line}</p>`);
  }
  if (listOpen) output.push("</ul>");
  return output.join("\n");
}

const [changelog, decisions] = await Promise.all([
  readFile(new URL("../CHANGELOG.md", import.meta.url), "utf8"),
  readFile(new URL("../DECISIONS.md", import.meta.url), "utf8")
]);

const body = `${render(changelog)}<hr>${render(decisions)}`;
const html = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Публичный журнал WOCLUB</title><style>body{margin:auto;max-width:850px;padding:3rem 1.25rem;background:#101713;color:#e8f0e8;font:16px/1.6 ui-monospace,monospace}h1{color:#b9f36c}h2{margin-top:2.5rem;border-top:1px solid #34453f;padding-top:1.5rem}p,li{color:#b8c5c0}a{color:#b9f36c}hr{margin:4rem 0;border:0;border-top:3px solid #b9f36c}</style></head><body><p><a href="/">← WOCLUB</a> · Создано из официальных журналов проекта CHANGELOG.md и DECISIONS.md.</p>${body}</body></html>`;

await writeFile(new URL("../src/generated-log.js", import.meta.url), `// Generated by npm run generate:log; do not edit.\nexport default ${JSON.stringify(html)};\n`);
